blueprint:
  name: Outdoor Lights – Independent Random Activity (Label Safe)
  description: >
    Turns lights on at sunset, randomly toggles individual lights
    during a night window, locks them on at the end of the window,
    and turns them off at sunrise. Supports labels, areas, and entities.
  domain: automation

  input:
    lights:
      name: Outdoor Lights (Labels / Areas / Entities)
      description: Select a label group, area, or individual lights
      selector:
        target: {}

    random_start:
      name: Random Activity Start Time
      default: "23:00:00"
      selector:
        time: {}

    random_end:
      name: Random Activity End Time
      default: "04:30:00"
      selector:
        time: {}

    min_events:
      name: Minimum Random Events Per Night
      default: 2
      selector:
        number:
          min: 0
          max: 20
          step: 1

    max_events:
      name: Maximum Random Events Per Night
      default: 8
      selector:
        number:
          min: 1
          max: 30
          step: 1

    min_delay:
      name: Minimum Delay Between Events (minutes)
      default: 10
      selector:
        number:
          min: 1
          max: 180
          step: 5
          unit_of_measurement: minutes

    max_delay:
      name: Maximum Delay Between Events (minutes)
      default: 60
      selector:
        number:
          min: 5
          max: 240
          step: 5
          unit_of_measurement: minutes

trigger:
  - platform: sun
    event: sunset
    id: sunset

  - platform: time
    at: !input random_start
    id: random_start

  - platform: time
    at: !input random_end
    id: random_end

  - platform: sun
    event: sunrise
    id: sunrise

variables:
  lights_list: >
    {{
      expand(lights.entity_id | default([], true))
      | selectattr('domain', 'eq', 'light')
      | map(attribute='entity_id')
      | list
    }}
  event_count: >
    {{ range(min_events | int, max_events | int + 1) | random }}

action:
  - choose:

      - conditions:
          - condition: trigger
            id: sunset
        sequence:
          - service: light.turn_on
            target: !input lights

      - conditions:
          - condition: trigger
            id: random_start
        sequence:
          - repeat:
              count: "{{ event_count }}"
              sequence:
                - delay:
                    minutes: >
                      {{ range(min_delay | int, max_delay | int + 1) | random }}
                - condition: sun
                  before: sunrise
                - variables:
                    chosen_light: "{{ lights_list | random }}"
                - service: light.toggle
                  target:
                    entity_id: "{{ chosen_light }}"

      - conditions:
          - condition: trigger
            id: random_end
        sequence:
          - service: light.turn_on
            target: !input lights

      - conditions:
          - condition: trigger
            id: sunrise
        sequence:
          - service: light.turn_off
            target: !input lights

mode: restart
