blueprint:
  name: Outdoor Lights – Random Night Activity
  description: >
    Turns lights on at sunset, randomly toggles them between two times,
    locks them on at the end of the window, and turns them off at sunrise.
  domain: automation

  input:
    lights:
      name: Outdoor Lights
      selector:
        target:
          entity:
            domain: light

    random_start:
      name: Random Activity Start Time
      default: "23:00:00"
      selector:
        time: {}

    random_end:
      name: Random Activity End Time
      default: "04:30:00"
      selector:
        time: {}

    min_toggles:
      name: Minimum Toggles Per Night
      default: 1
      selector:
        number:
          min: 0
          max: 10
          step: 1

    max_toggles:
      name: Maximum Toggles Per Night
      default: 4
      selector:
        number:
          min: 1
          max: 15
          step: 1

    min_delay:
      name: Minimum Delay Between Toggles (minutes)
      default: 20
      selector:
        number:
          min: 5
          max: 180
          step: 5
          unit_of_measurement: minutes

    max_delay:
      name: Maximum Delay Between Toggles (minutes)
      default: 90
      selector:
        number:
          min: 10
          max: 240
          step: 5
          unit_of_measurement: minutes

trigger:
  - platform: sun
    event: sunset
    id: sunset

  - platform: time
    at: !input random_start
    id: random_start

  - platform: time
    at: !input random_end
    id: random_end

  - platform: sun
    event: sunrise
    id: sunrise

variables:
  toggle_count: >
    {{ range(min_toggles | int, max_toggles | int + 1) | random }}
  delay_minutes: >
    {{ range(min_delay | int, max_delay | int + 1) | random }}

action:
  - choose:

      # 🌇 Sunset → ON
      - conditions:
          - condition: trigger
            id: sunset
        sequence:
          - service: light.turn_on
            target: !input lights

      # 🌙 Random activity window
      - conditions:
          - condition: trigger
            id: random_start
        sequence:
          - repeat:
              count: "{{ toggle_count }}"
              sequence:
                - delay:
                    minutes: "{{ range(min_delay | int, max_delay | int + 1) | random }}"
                - condition: sun
                  before: sunrise
                - service: light.toggle
                  target: !input lights

      # 🔒 Lock lights ON at end of window
      - conditions:
          - condition: trigger
            id: random_end
        sequence:
          - service: light.turn_on
            target: !input lights

      # 🌅 Sunrise → OFF
      - conditions:
          - condition: trigger
            id: sunrise
        sequence:
          - service: light.turn_off
            target: !input lights

mode: restart
