blueprint:
  name: CO₂ Alert (Multi-Sensor)
  description: Multi-sensor CO₂ alert with mobile notifications and optional script runner.
  domain: automation

  input:
    co2_sensors:
      name: CO₂ Sensors
      description: Select one or more CO₂ sensors to monitor.
      selector:
        entity:
          multiple: true
          domain: sensor
          device_class: carbon_dioxide

    threshold:
      name: Alert Threshold (ppm)
      description: CO₂ level that triggers the alert for all sensors.
      default: 1000
      selector:
        number:
          min: 400
          max: 2000
          step: 50
          unit_of_measurement: ppm

    notify_device:
      name: "Devices to Notify"
      description: "Select mobile devices to receive notifications."
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true

    optional_script:
      name: Script to Run (Optional)
      description: Script to run when the alert is triggered.
      default: ""
      selector:
        entity:
          domain: script

    action_conditions:
      name: Action Conditions (Optional)
      description: Additional conditions required before notifications or script run.
      default: []
      selector:
        condition: {}

    duration:
      name: Time Above Threshold
      description: How long the sensor must stay above the threshold before alerting.
      default:
        minutes: 2
      selector:
        duration: {}

trigger:
  - platform: numeric_state
    entity_id: !input co2_sensors
    above: !input threshold
    for: !input duration
    id: alert_start
  - platform: numeric_state
    entity_id: !input co2_sensors
    below: !input threshold
    id: alert_clear
  - platform: state
    entity_id: !input co2_sensors
    id: alert_update

variables:
  co2_sensors_list: !input co2_sensors
  triggered_sensor: "{{ trigger.entity_id if trigger.entity_id is defined else co2_sensors_list[0] }}"
  current_co2: "{{ states(triggered_sensor) | float(0) }}"
  sensor_name: "{{ state_attr(triggered_sensor, 'friendly_name') or 'Unknown Sensor' }}"
  device_name: >
    {%- set dev_id = state_attr(triggered_sensor, 'device_id') -%}
    {%- if dev_id -%}
      {{ device_attr(dev_id, 'name') or 'Unknown Device' }}
    {%- else -%}
      Unknown Device
    {%- endif -%}
  room_name: "{{ area_name(triggered_sensor) or 'Unknown Room' }}"
  threshold_ppm: !input threshold
  optional_script: !input optional_script

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: alert_clear
        sequence:
          - repeat:
              for_each: !input notify_device
              sequence:
                - if: "{{ device_attr(repeat.item, 'name') is not none }}"
                  then:
                    - service: notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}
                      data:
                        message: "clear_notification"
                        data:
                          tag: "co2_alert_{{ triggered_sensor | replace('.', '_') }}"

      - conditions:
          - condition: trigger
            id:
              - alert_start
              - alert_update
          - condition: template
            value_template: >
              {% if trigger.id == 'alert_update' %}
                {{ trigger.from_state is defined and trigger.from_state is not none and trigger.from_state.state | float(0) >= threshold_ppm and trigger.to_state.state | float(0) >= threshold_ppm }}
              {% else %}
                true
              {% endif %}
          - condition: and
            conditions: !input action_conditions
        sequence:
          - repeat:
              for_each: !input notify_device
              sequence:
                - if: "{{ device_attr(repeat.item, 'name') is not none }}"
                  then:
                    - service: notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}
                      data:
                        title: "🚨 High CO₂ Alert > {{ threshold_ppm }} ppm"
                        message: >
                          {{ sensor_name }}
                          {% if device_name != 'Unknown Device' %}({{ device_name }}){% endif %}
                          has reached {{ current_co2 }} ppm CO₂
                          {% if room_name != 'Unknown Room' %}in {{ room_name }}{% endif %}
                          (threshold: {{ threshold_ppm }} ppm).
                        data:
                          tag: "co2_alert_{{ triggered_sensor | replace('.', '_') }}"
                          sticky: "true"
                          persistent: true
                          channel: co2_alerts

          - if: "{{ trigger.id == 'alert_start' and optional_script is not none and optional_script != '' }}"
            then:
              - service: script.turn_on
                data:
                  entity_id: "{{ optional_script }}"


mode: parallel
max: 10
