# Home/Away Thermostat Control by Zone
# This blueprint automatically adjusts your thermostat mode based on occupancy and time.
# Requirements:
#   - Home Assistant with a select entity for thermostat mode control
#   - A zone.home entity tracking occupancy (0 = away, 1+ = someone home)
#   - Your script must have a select.select_option action with home/sleep/away options
#
# How to find your select entity:
#   1. Go to Developer Tools > States
#   2. Look for entities like "select.thermostat_mode" or similar
#   3. Click on it and verify it has "home", "sleep", and "away" options
#
# How it works:
#   - When zone.home < 1: Sets select entity to Away option
#   - When zone.home >= 1 and during sleep hours: Sets to Sleep option
#   - When zone.home >= 1 and NOT during sleep hours: Sets to Home option
#   - Triggers on occupancy changes and every 15 minutes to catch time-based transitions
#
blueprint:
  name: Home/Away Thermostat Control by Zone
  description: >-
    Controls thermostat mode select entity based on zone.home occupancy and time of day.
    If someone is home, set to Home or Sleep mode. If no one is home, set to Away.
  domain: automation
  input:
    thermostat_select:
      name: Thermostat Mode Select Entity
      description: >-
        The select entity that controls your thermostat mode
        (e.g., select.main_floor_mode). Must have home, sleep, and away options.
      selector:
        entity:
          domain: select
          multiple: false
    home_option:
      name: Home mode option
      description: >-
        The option value to send when someone is home and it is NOT sleep time.
        Typically: "home"
      default: home
      selector:
        text:
    sleep_option:
      name: Sleep mode option
      description: >-
        The option value to send when someone is home DURING sleep hours.
        Typically: "sleep"
      default: sleep
      selector:
        text:
    away_option:
      name: Away mode option
      description: >-
        The option value to send when nobody is home (zone.home < 1).
        Typically: "away"
      default: away
      selector:
        text:
    sleep_start:
      name: Sleep start time
      description: >-
        Time of day when sleep mode begins (e.g., 22:00 for 10 PM).
        Format: HH:MM:SS
      default: "22:00:00"
      selector:
        time:
    sleep_end:
      name: Sleep end time
      description: >-
        Time of day when sleep mode ends (e.g., 06:00 for 6 AM).
        Format: HH:MM:SS. Can be earlier than sleep_start for overnight periods.
      default: "06:00:00"
      selector:
        time:

mode: single

# Triggers when:
# 1. Someone arrives home (zone.home goes above 0)
# 2. Everyone leaves (zone.home goes below 1)
# Also triggers periodically to check if time-based mode needs to change
trigger:
  - platform: numeric_state
    entity_id: zone.home
    below: 1
  - platform: numeric_state
    entity_id: zone.home
    above: 0
  - platform: time_pattern
    minutes: "/15"

# Store input values as variables for use in conditions
variables:
  sleep_start: !input sleep_start
  sleep_end: !input sleep_end

# Determine which preset to apply based on occupancy and time
action:
  - choose:
      # If nobody is home (zone.home < 1), set to away preset
      - conditions:
          - condition: numeric_state
            entity_id: zone.home
            below: 1
        sequence:
          - service: select.select_option
            target:
              entity_id: !input thermostat_select
            data:
              option: !input away_option
      # If someone is home AND it's sleep time, set to sleep preset
      - conditions:
          - condition: numeric_state
            entity_id: zone.home
            above: 0
          - condition: template
            value_template: >-
              {% set now_time = now().time() %}
              {% if sleep_start < sleep_end %}
                {{ now_time >= sleep_start and now_time < sleep_end }}
              {% else %}
                {{ now_time >= sleep_start or now_time < sleep_end }}
              {% endif %}
        sequence:
          - service: select.select_option
            target:
              entity_id: !input thermostat_select
            data:
              option: !input sleep_option
    # Otherwise (someone is home and NOT sleep time), set to home preset
    default:
      - service: select.select_option
        target:
          entity_id: !input thermostat_select
        data:
          option: !input home_option
