blueprint:
  name: Outdoor Lights – Independent Random Activity (Improved)
  description: Randomly toggles individual outdoor lights overnight
  domain: automation
  input:
    lights:
      name: Outdoor Lights
      description: Select labels, areas, or lights
      selector:
        target: {}
    random_start:
      name: Random Start Time
      description: The time lights should start randomly turning on or off
      default: '23:00:00'
      selector:
        time: {}
    duration_minutes:
      name: Duration (minutes)
      description: How long the random events should continue
      default: 360
      selector:
        number:
          min: 15.0
          max: 600.0
          step: 15.0
          mode: slider
          unit_of_measurement: minutes
    min_events:
      name: Minimum Events
      description: Minimum number of random toggle events
      default: 2
      selector:
        number:
          min: 0.0
          max: 20.0
          step: 1.0
          mode: slider
    max_events:
      name: Maximum Events
      description: Maximum number of random toggle events
      default: 8
      selector:
        number:
          min: 1.0
          max: 30.0
          step: 1.0
          mode: slider
    min_delay:
      name: Minimum Delay (minutes)
      description: Minimum delay between toggle events
      default: 10
      selector:
        number:
          min: 1.0
          max: 180.0
          step: 5.0
          mode: slider
    max_delay:
      name: Maximum Delay (minutes)
      description: Maximum delay between toggle events
      default: 60
      selector:
        number:
          min: 5.0
          max: 240.0
          step: 5.0
          mode: slider
    enable_notifications:
      name: Enable Notifications
      description: Show notifications for each toggle event
      default: false
      selector:
        boolean: {}

trigger:
  - platform: sun
    event: sunset
    id: sunset
  - platform: time
    at: !input random_start
    id: random_start
  - platform: sun
    event: sunrise
    id: sunrise

variables:
  v_lights: !input lights
  v_duration_minutes: !input duration_minutes
  v_min_events: !input min_events
  v_max_events: !input max_events
  v_min_delay: !input min_delay
  v_max_delay: !input max_delay
  v_notifications: !input enable_notifications

  # Fixed: Properly expand all target types (label, area, device, entity)
  lights_list: >-
    {% set ns = namespace(entities=[]) %}
    {% if v_lights.entity_id is defined %}
      {% set ns.entities = ns.entities + v_lights.entity_id %}
    {% endif %}
    {% if v_lights.area_id is defined %}
      {% set areas = v_lights.area_id if v_lights.area_id is iterable and v_lights.area_id is not string else [v_lights.area_id] %}
      {% for area in areas %}
        {% set ns.entities = ns.entities + (area_entities(area) | select('match', '^light\.') | list) %}
      {% endfor %}
    {% endif %}
    {% if v_lights.device_id is defined %}
      {% set devices = v_lights.device_id if v_lights.device_id is iterable and v_lights.device_id is not string else [v_lights.device_id] %}
      {% for device in devices %}
        {% set ns.entities = ns.entities + (device_entities(device) | select('match', '^light\.') | list) %}
      {% endfor %}
    {% endif %}
    {% if v_lights.label_id is defined %}
      {% set labels = v_lights.label_id if v_lights.label_id is iterable and v_lights.label_id is not string else [v_lights.label_id] %}
      {% for label in labels %}
        {% set ns.entities = ns.entities + (label_entities(label) | select('match', '^light\.') | list) %}
      {% endfor %}
    {% endif %}
    {{ ns.entities | unique | list }}

  event_count: >-
    {{ range((v_min_events | int), (v_max_events | int) + 1) | random }}

  sequence_end_time: >-
    {{ now() + timedelta(minutes=(v_duration_minutes | int)) }}

condition: []

action:
  - choose:
      # SUNSET: Turn all lights on
      - conditions:
          - condition: trigger
            id: sunset
        sequence:
          - service: light.turn_on
            target: !input lights

      # RANDOM START: Begin random toggle sequence
      - conditions:
          - condition: trigger
            id: random_start
          - condition: template
            value_template: '{{ lights_list | length > 0 }}'
          - condition: sun
            before: sunrise
        sequence:
          - if:
              - condition: template
                value_template: '{{ v_notifications }}'
            then:
              - service: persistent_notification.create
                data:
                  title: "🌙 Random Lighting Started"
                  message: >-
                    Events: {{ event_count }} | Duration: {{ v_duration_minutes }}min
          
          - repeat:
              count: '{{ event_count }}'
              sequence:
                # Stop if duration exceeded or sunrise
                - condition: template
                  value_template: '{{ now() < sequence_end_time }}'
                - condition: sun
                  before: sunrise
                
                # Random delay and light selection
                - variables:
                    delay_minutes: >-
                      {{ range((v_min_delay | int), (v_max_delay | int) + 1) | random }}
                    selected_light: '{{ lights_list | random }}'
                
                # Wait
                - delay:
                    minutes: '{{ delay_minutes }}'
                
                # Final check before toggling
                - condition: template
                  value_template: '{{ now() < sequence_end_time }}'
                - condition: sun
                  before: sunrise
                
                # Toggle the light
                - service: light.toggle
                  target:
                    entity_id: '{{ selected_light }}'
                
                # Optional notification
                - if:
                    - condition: template
                      value_template: '{{ v_notifications }}'
                  then:
                    - service: persistent_notification.create
                      data:
                        title: "💡 Light Toggled ({{ repeat.index }}/{{ event_count }})"
                        message: >-
                          {{ state_attr(selected_light, 'friendly_name') }}: {{ states(selected_light) | upper }}
          
          # After sequence, turn all lights back on
          - service: light.turn_on
            target: !input lights

      # SUNRISE: Turn all lights off
      - conditions:
          - condition: trigger
            id: sunrise
        sequence:
          - service: light.turn_off
            target: !input lights

mode: restart
